### ISSUE TITLE
How to evaluate on other datasets and save results?

### ISSUE THREAD

**Issue by koubun-ko-df** [daodaofr/hypergraph_reid#12]
Hello, I want to check the performance of this method on my dataset. However, it only provides the way to train. May I ask how to evaluate with the trained model, and how to save the results? 
Thank you!

**Comment by daodaofr** [comment]
the test code is here: https://github.com/daodaofr/hypergraph_reid/blob/7485b89667b5e9f5de95d50f9f5a21b2fcb28045/main_video_person_reid_hypergraphsage_part.py#L281
