### ISSUE TITLE
code availability: is there any update?

### ISSUE THREAD

**Issue by jpainam** [daodaofr/hypergraph_reid#2]
any update on the code?

**Comment by daodaofr** [comment]
I will try my best to do it as soon as possible.

**Comment by ToumaKazusa3** [comment]
could you please  release the code of **Algorithm 1 Hypergraph Propagation**

**Comment by Xxxia96** [comment]
Could you prepare to release the code recently? I will be grateful if you can release it as soon as possible. @daodaofr

**Comment by daodaofr** [comment]
I am working on it, hopefully it would be done in the following week. @Sophie-Xu

**Comment by Xxxia96** [comment]
>     I am working on it, hopefully it would be done in the following week. @Sophie-Xu 

- okay. Tnanks for your reply and I will keep focus on your work.
