### ISSUE TITLE
loss converges to 4.4, map only reaches 60.0%, rank1 only reaches 73.3%, learning rate is set to 0.000075, and the step size is 100.

### ISSUE THREAD

**Issue by Seven-gcc** [daodaofr/hypergraph_reid#6]
I use GeForce RTX 2080 with 7G memory, loss converges to 4.4, map only reaches 60.0%, rank1 only reaches 73.3%, batchsize is set to 8,learning rate is set to 0.000075, and the step size is 100.
Because there was not enough memory during the test, only a part of it was loaded. Do you think it is the parameter setting or too little test load data? I adjusted it several times, but the effect was not satisfactory.
Thank you ！

**Comment by daodaofr** [comment]
I think the combination of batch size and learning rate may impact the performance. 
Sorry, I didn't tried batchsize=8, so I cannot give much suggestion.

About the memory issue, you may extract the features part by part, and then evaluate it.

**Comment by Seven-gcc** [comment]
Thank you for your reply! I  will try again,hoping it will be ok!

**Comment by Seven-gcc** [comment]
Hello！I want to confirm a few questions. To what extent can your loss function finally converge? What is the accuracy of  the  code that you published?map 84.1,rank1 88.7? I want to confirm that whether the code excludes Lmi and Att. The loss I reproduced can only converge to about 4.
Thank you very much.

**Comment by daodaofr** [comment]
Hi, yes, this code does not contain Lmi and Att, these two terms have a limited impact on the overall performance. 
Normally, this code can achieve map ~85, rank1 ~89. 
I will check and upload a trained model soon,  for you to reproduce the performance.

**Comment by Seven-gcc** [comment]
It would be great if you can upload the trained model. I tried for a long time but still didn't reproduce it.Thank you again!!

**Comment by daodaofr** [comment]
Don't worry, I will use this code to train the model, normally it will finish training in 10 days. I will get back to you as soon as possible.

**Comment by Seven-gcc** [comment]
Thank you very much!! That will help me a lot!!

**Comment by daodaofr** [comment]
I've trained 200 epochs, the result seems normal. I get mAP 80% and rank-1 85% for now.
You may find the trained model helpful: 
https://drive.google.com/file/d/164jD6fxQISl1HFkkjKmCCwPOTDaQT_gu/view?usp=sharing

**Comment by Seven-gcc** [comment]
Thank you for your excellent work!! Maybe the batch size has an important effect on the performance.
All in all, thank you very much for your help！

**Comment by khawar-islam** [comment]
@Seven-gcc Do you get this error? "Will redo. Don't worry. Just chill". I just put the dataset inside mars folder and align all the folders but this error happened.

**Comment by Seven-gcc** [comment]
Sorry, I did not meet the problem. It is my regret that I cannot help you.
















在 2021-03-18 20:24:54，"Khawar Islam" ***@***.***> 写道：

@Seven-gcc Do you get this error? "Will redo. Don't worry. Just chill". I just put the dataset inside mars folder and align all the folders but this error happened.

**Comment by khawar-islam** [comment]
Did you get this error?
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by Seven-gcc** [comment]
I think that belongs to your environmental problems. Sorry I have not encountered.

**Comment by khawar512** [comment]
Ok.

**Comment by khawar512** [comment]
@Seven-gcc  I solved this error. Still gets CUDA out of memory when my batch size in 1. I have 16GB RAM and training on RTX 2070. Help required please

**Comment by Seven-gcc** [comment]
Sorry,I gave up the frame work and I did'nt reproduce the performance.



At 2021-03-20 20:13:09, "Khawar Islam" ***@***.***> wrote:

@Seven-gcc I solved this error. Still gets CUDA out of memory when my batch size in 1. I have 16GB RAM and training on RTX 2070. Help required please
