### ISSUE TITLE
BatchedGraphSAGEDynamicRangeMean1类中的实现只有一种时间尺度？

### ISSUE THREAD

**Issue by xuangch** [daodaofr/hypergraph_reid#9]
作者您好！对您的工作十分感兴趣，但根据源码里ResNet50GRAPHPOOLPARTHyper和BatchedGraphSAGEDynamicRangeMean1这两个类的相关实现，似乎只使用了一个时间粒度（3）？谢谢！

**Comment by xuangch** [comment]
不好意思我误点了之前commit的代码，打扰了

**Comment by daodaofr** [comment]
def forward(self, x, adj, p, t) 这个t 代表时间尺度，这里只用了3，可以用多个，效果稍微好一点，但是影响并不太大。
